Config = Config or {}
Config.BillingCommissions = { -- This is a percentage (0.10) == 10%
    mechanic = 0.10
}
Config.Linux = false      -- True if linux
Config.TweetDuration = 12 -- How many hours to load tweets (12 will load the past 12 hours of tweets)
Config.RepeatTimeout = 2000
Config.CallRepeats = 10
Config.OpenPhone = 244
Config.PhoneApplications = {
    ['phone'] = {
        app = 'phone',
        -- color = '#04b543',
        -- icon = 'fa fa-phone-alt',
        tooltipText = 'Phone',
        tooltipPos = 'top',
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ['whatsapp'] = {
        app = 'whatsapp',
        -- color = '#25d366',
        -- icon = 'fas fa-comment',
        tooltipText = 'Whatsapp',
        tooltipPos = 'top',
        style = 'font-size: 2.8vh',
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
    },
    ['settings'] = {
        app = 'settings',
        -- color = '#636e72',
        -- icon = 'fa fa-cogs',
        tooltipText = 'Settings',
        tooltipPos = 'top',
        style = 'padding-right: .08vh; font-size: 2.3vh',
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ['twitter'] = {
        app = 'twitter',
        -- color = '#1da1f2',
        -- icon = 'fab fa-twitter',
        tooltipText = 'Twitter',
        tooltipPos = 'top',
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    ['garage'] = {
        app = 'garage',
        -- color = '#575fcf',
        -- icon = 'fas fa-car',
        tooltipText = 'Vehicles',
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
    ['mail'] = {
        app = 'mail',
        -- color = '#ff002f',
        -- icon = 'fas fa-envelope-open-text',
        tooltipText = 'Mail',
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
    },
    ['advert'] = {
        app = 'advert',
        -- color = '#ff8f1a',
        -- icon = 'fas fa-bullhorn',
        tooltipText = 'Advertisements',
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
    },
    ['bank'] = {
        app = 'bank',
        -- color = '#9c88ff',
        -- icon = 'fas fa-money-check-alt',
        tooltipText = 'Bank',
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
    },
    ['crypto'] = {
        app = 'crypto',
        -- color = '#004682',
        -- icon = 'fas fa-coins',
        tooltipText = 'Crypto',
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },
    ['racing'] = {
        app = 'racing',
        -- color = '#353b48',
        -- icon = 'fas fa-flag-checkered',
        tooltipText = 'Racing',
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
    },
    ['houses'] = {
        app = 'houses',
        -- color = '#27ae60',
        -- icon = 'fas fa-home',
        tooltipText = 'Houses',
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    },
    ['lawyers'] = {
        app = 'lawyers',
        -- color = '#26d4ce',
        -- icon = 'fas fa-briefcase',
        tooltipText = 'Services',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    },
    ['gallery'] = {
        app = 'gallery',
        -- color = '#AC1D2C',
        -- icon = 'fas fa-images',
        tooltipText = 'Gallery',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
    ['camera'] = {
        app = 'camera',
        -- color = '#AC1D2C',
        -- icon = 'fas fa-camera',
        tooltipText = 'Camera',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    },
    ["ping"] = {
        app = "ping",
        icon = "fas fa-map-marker-alt",
        tooltipText = "Google Maps",
        tooltipPos = "top",
        style = "font-size: 3.3vh";
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
    },
    ["calculator"] = {
        app = "calculator",
        color = "#c94001",
        color2 = "#9c3100",
        icon = "fas fa-calculator",
        tooltipText = "Calculator",
        tooltipPos = "bottom",
        style = "font-size: 2.5vh";
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
    },
    ['meos'] = {
        app = 'meos',
        -- color = '#004682',
        -- icon = 'fas fa-ad',
        tooltipText = 'MDT',
        job = 'police',
        blockedjobs = {},
        slot = 17,
        Alerts = 0,
    },
}
Config.MaxSlots = 20

Config.StoreApps = {
    ['territory'] = {
        app = 'territory',
        color = '#353b48',
        icon = 'fas fa-globe-europe',
        tooltipText = 'Territorium',
        tooltipPos = 'right',
        style = '',
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
        password = true,
        creator = 'QBCore',
        title = 'Territory',
    },
}
